Recursively search for stack config under stacks directory
sparkleformation/sfn-parameters pull request #13
Opened 2017-08-29 11:16 UTC by jimcroft

Convenience feature to allow stack files to exist anywhere under the stacks directory.

Much like template files can exists anywhere under the templates directory our users would like the same behavior in stacks. It allows them to organize stack files however they see fit.

There might be a downside or problem doing this but not sure what that'd be. :)

2017-08-30 02:59 UTC, chrisroberts requested changes

2017-08-30 02:59 UTC, chrisroberts commented on lib/sfn-parameters/stacks.rb
> +        root_path = config.fetch(:sfn_parameters, :directory, 'stacks', '**')
This modification would change the configuration location for the directory path from:

```ruby
{sfn_parameters: {directory: 'PATH'}}
```

with `"stacks"` being the default directory to:

```ruby
{sfn_parameters: {directory: {stacks: 'PATH'}}}
```

with `"*"` being the default value. The `Smash#fetch` method works much like the `Hash#dig` method (just before `#dig` was available). Were you thinking of something like:

```ruby
root_path = config.fetch(:sfn_parameters, :directory, "stacks#{File::DELIMITER}*")
```

2017-08-30 03:03 UTC, chrisroberts commented
@jimcroft Hi! So the problem this would introduce is that the file names correspond to specific stacks. This is how sfn knows which file to load when creating/updating a stack. Can you describe the type of behavior you're trying to accomplish? I understand the ability to let the files be located anywhere, but if the file name does not match the stack name I'm not sure how we can determine which file to apply.

2017-09-13 09:50 UTC, jimcroft commented
Thanks for the feedback Chris.

So the stack filename itself would still have to match the stack name, no change there. It's more that we want to have an arbitrary directory structure under stacks. So something like this would be possible:

```
/stacks
  /dev
    dev-web.rb
    dev-db.rb
  /prod
    prod-web.rb
    prod-db.rb
``` 

This is very much a cosmetic-would-be-nice feature (so no big deal if kicked to the kerb) but does cause a bit of confusion when devs can create templates, components, etc. where ever they like (so long as the template/component name is unique).

2019-04-05 23:59 UTC, siulcode commented
Hey guys, 

I know this is an old thread, but I am kinda hitting something similar. 

Is there any way to inject custom configuration files (yaml) in app directories into sparkle? 

Below is my directory structure, we were using a similar directory structure with a different tool, but a new requirement changed with the need of the "Cloud-agnostic" feature, hence we ended up using SparkleFormation and it seems to be an awesome tool so far. 
 
Structure: 
`├───components
├───conf
│   ├───apps
│   │   ├───app1 >> [EC2,SG,LB].yaml
│   │   └───app2 >> [EC2,SG,LB].yaml
│   └───environment >> main.yaml
├───dynamics
└───registry
`
If there's anything else we can do or any other way to achieve this it would be greatly appreciated!

Thanks again for the great support.

cc.: @chrisroberts

2020-12-07 09:56 UTC, closed without merging